name: Migrate Database
on: 
  workflow_dispatch:
    inputs:
      src_host:
        description: 'Source Database Host Name'
        required: true
        default: 'Unknown'
        type: string
      src_database:
        description: 'Source Database Name'
        required: true
        default: 'Unknown'
        type: string
      src_db_user_kv_key:
        description: 'Keyvalut Key for Database Username'
        required: true
        default: 'Unknown'
        type: string
      src_db_password_kv_key:
        description: 'Keyvault Key for Database User Password'
        required: true
        default: 'Unknown'
        type: string
      dest_host:
        description: 'Destination Database Host Name'
        required: true
        default: 'Unknown'
        type: string
      dest_database:
        description: 'Destination Database Name'
        required: true
        default: 'Unknown'
        type: string
      dest_db_user_kv_key:
        description: 'Keyvalut Key for Database Username'
        required: true
        default: 'Unknown'
        type: string
      dest_db_password_kv_key:
        description: 'Keyvalut Key for Database User Password'
        required: true
        default: 'Unknown'
        type: string
jobs:
  database:
    runs-on: ubuntu-latest
    name: database
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: Azure/get-keyvault-secrets@v1
        with: 
          keyvault: "containervault"
          secrets: 'src_user, src_user_password, dest_user, dest_password'
        id: get_secrets
      - name: Migrate Database
        uses: ./database
        env:
          src_host: ${{ inputs.src_host }}
          src_database: ${{ inputs.src_database }}          
          src_user: ${{ steps.get_secrets.outputs.src_user }}
          src_user_password: ${{ steps.get_secrets.outputs.src_user_password }}       
          dest_host: ${{ inputs.dest_host }}
          dest_database: ${{ inputs.dest_database }}          
          dest_user: ${{ steps.get_secrets.outputs.dest_user }}
          dest_user_password: ${{ steps.get_secrets.outputs.dest_password }}