name: Platform Management
on:
  workflow_dispatch:
    inputs:
      provisionConnectivity:
        description: 'Provision Connectivity'
        type: boolean
        required: false
      provisionCommonServices:
        description: 'Provision Common Services Resources'
        type: boolean
        required: false
      location:
        description: 'Resource Group location'
        required: true
        default: 'westus3'
        type: string
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - production

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:

  Connectivity_Resources:
    name: Create Connectivity Resources
    runs-on: ubuntu-latest
    if: |
      !failure() && !cancelled() &&
      (
        github.event.inputs.provisionConnectivity == 'true' ||
        (github.event_name == 'push' && github.ref == 'refs/heads/dev')
      )
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: OIDC Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Create Resources
        id: task-create-resources
        run: |

          # Get params
          target_env=${{github.event.inputs.environment}}
          location=${{github.event.inputs.location}}

          echo create provision_connectivity in $location
          ./script/devops.sh provision_connectivity --location "$location"

  Common_Services_Resources:
    name: Create Common Services Resources
    runs-on: ubuntu-latest
    if: |
      !failure() && !cancelled() &&
      (
        github.event.inputs.provisionCommonServices == 'true' ||
        (github.event_name == 'push' && github.ref == 'refs/heads/dev')
      )
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: OIDC Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Create Resources
        id: task-create-resources
        run: |

          # Get params
          target_env=${{github.event.inputs.environment}}
          rg_region=${{github.event.inputs.location}}

          echo create provision_connectivity in $location
          ./script/devops.sh provision_connectivity --location "$location"
